In [1]:
import boto3
import s3fs
import xarray as xr
import fsspec

# Define the URLs for the datasets
precip_url = 's3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr'
temp_url = 's3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr'
humid_url = 's3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr'

# Load the datasets using xarray and fsspec
precip_ds = xr.open_zarr(fsspec.get_mapper(precip_url, anon=True), consolidated=True)
temp_ds = xr.open_zarr(fsspec.get_mapper(temp_url, anon=True), consolidated=True)
humid_ds = xr.open_zarr(fsspec.get_mapper(humid_url, anon=True), consolidated=True)

# Merge the datasets
combined_ds = xr.merge([temp_ds, precip_ds, humid_ds])

# Rename variables for clarity
combined_ds = combined_ds.rename({
    'T2D': 'temperature',
    'RAINRATE': 'total_precipitation',
    'Q2D': 'specific_humidity'
})

print(combined_ds)



precip_ds['RAINRATE'].isel(time=slice(0, 100), x=slice(1000, 1010), y=slice(1000, 1010)).values

<xarray.Dataset> Size: 136TB
Dimensions:              (time: 385704, y: 3840, x: 4608)
Coordinates:
  * time                 (time) datetime64[ns] 3MB 1979-02-01 ... 2023-01-31T...
  * x                    (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.304e+06
  * y                    (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.919e+06
Data variables:
    temperature          (time, y, x) float64 55TB ...
    crs                  |S1 1B b''
    total_precipitation  (time, y, x) float32 27TB ...
    specific_humidity    (time, y, x) float64 55TB ...
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing


In [26]:
precip_ds['RAINRATE'].isel(time=slice(0, 100), x=slice(1000, 1010), y=slice(1000, 1010)).values

array([[[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        ...,
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00]],

       [[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.000

In [27]:
temp_ds['T2D'].isel(time=slice(0, 100), x=slice(1000, 1010), y=slice(1000, 1010)).values

array([[[285.26, 285.59, 285.72, ..., 285.19, 285.02, 284.84],
        [285.06, 285.38, 285.52, ..., 285.13, 285.  , 284.82],
        [284.8 , 285.23, 285.33, ..., 285.02, 284.91, 284.77],
        ...,
        [284.23, 284.44, 284.66, ..., 283.86, 284.  , 283.98],
        [283.88, 284.19, 284.48, ..., 283.79, 283.71, 283.65],
        [283.66, 283.99, 284.24, ..., 283.77, 283.54, 283.45]],

       [[282.4 , 282.69, 282.73, ..., 282.23, 282.05, 281.88],
        [282.16, 282.48, 282.55, ..., 282.12, 282.09, 281.88],
        [281.91, 282.32, 282.38, ..., 282.02, 282.01, 281.86],
        ...,
        [281.43, 281.6 , 281.68, ..., 280.95, 281.08, 280.98],
        [281.17, 281.38, 281.58, ..., 280.78, 280.73, 280.66],
        [280.88, 281.13, 281.31, ..., 280.7 , 280.59, 280.48]],

       [[279.69, 279.9 , 279.93, ..., 279.42, 279.26, 279.08],
        [279.45, 279.71, 279.75, ..., 279.33, 279.27, 279.02],
        [279.2 , 279.56, 279.62, ..., 279.22, 279.21, 278.98],
        ...,
        [278

In [29]:
import pandas as pd
import os
HOME = os.path.expanduser('~')



pd.read_parquet(f"{HOME}/SWEMLv2.0/data/TrainingDFs/Southwest/300M_Resolution/Southwest_metadata.parquet")

cen_lat     cen_lon  Elevation_m  Slope_Deg  \
cell_id                                                                         
Southwest_300M_37.819_-119.271  37.818860 -119.271489         3170         51   
Southwest_300M_37.819_-119.269  37.818860 -119.268789         3191         23   
Southwest_300M_37.819_-119.266  37.818860 -119.266089         3300         53   
Southwest_300M_37.819_-119.263  37.818860 -119.263389         3428         37   
Southwest_300M_37.819_-119.261  37.818860 -119.260689         3535          8   
...                                   ...         ...          ...        ...   
Southwest_300M_36.67_-119.038   36.670492 -119.037762         2163         29   
Southwest_300M_36.67_-119.03    36.670492 -119.029662         2158          9   
Southwest_300M_36.67_-119.027   36.670492 -119.026962         2172          6   
Southwest_300M_36.668_-119.03   36.667792 -119.029662         2158          9   
Southwest_300M_36.668_-119.027  36.667792 -119.026962         2172          6   

                                Aspect_Deg  
cell_id                                     
Southwest_300M_37.819_-119.271         230  
Southwest_300M_37.819_-119.269         281  
Southwest_300M_37.819_-119.266         320  
Southwest_300M_37.819_-119.263         341  
Southwest_300M_37.819_-119.261         330  
...                                    ...  
Southwest_300M_36.67_-119.038           73  
Southwest_300M_36.67_-119.03            99  
Southwest_300M_36.67_-119.027          243  
Southwest_300M_36.668_-119.03           99  
Southwest_300M_36.668_-119.027         243  

[299555 rows x 5 columns]

In [2]:
# Check a small sample of raw data values directly from the source
raw_sample_temp = combined_ds['temperature'].isel(time=slice(0, 10), x=slice(0, 10), y=slice(0, 10)).values - 273.15
raw_sample_humidity = combined_ds['specific_humidity'].isel(time=slice(0, 10), x=slice(0, 10), y=slice(0, 10)).values
raw_sample_precip = combined_ds['total_precipitation'].isel(time=slice(0, 10), x=slice(0, 10), y=slice(0, 10)).values

print("Sample Raw Temperature Values (Celsius):")
print(raw_sample_temp)
print("Sample Raw Specific Humidity Values (kg/kg):")
print(raw_sample_humidity)
print("Sample Raw Precipitation Values (mm):")
print(raw_sample_precip)

Sample Raw Temperature Values (Celsius):
[[[14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]]

 [[14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.8

In [3]:
def subset_dataset(ds, year, month):
    # Define the bounding box coordinates
    min_x = -2303499.25
    max_x = 2303500.75
    min_y = -1919500.375
    max_y = 1919499.625

    # Define the time range for the month
    start_date = f'{year}-{month:02d}-01'
    if month == 12:
        end_date = f'{year+1}-01-01'
    else:
        end_date = f'{year}-{month+1:02d}-01'

    # Subset the dataset to the bounding box and the time range
    subset_ds = ds.sel(x=slice(min_x, max_x), y=slice(min_y, max_y), time=slice(start_date, end_date))

    return subset_ds


In [4]:
def calculate_wbt(temp_c, rh):
    wbt = temp_c * np.arctan(0.151977 * np.sqrt(rh + 8.313659)) + \
          np.arctan(temp_c + rh) - np.arctan(rh - 1.676331) + \
          0.00391838 * (rh ** (3 / 2)) * np.arctan(0.023101 * rh) - 4.686035
    return wbt

def calculate_relative_humidity(temp_c, specific_humidity):
    A = 6.1121  # hPa
    B = 17.502
    C = 240.97  # degrees Celsius
    saturation_vapor_pressure = A * np.exp((B * temp_c) / (temp_c + C))
    actual_vapor_pressure = specific_humidity * 1013.25 / (0.622 + 0.378 * specific_humidity)
    rh = (actual_vapor_pressure / saturation_vapor_pressure) * 100
    return rh

In [5]:
def add_wbt_and_precip_phase(ds):
    # Assuming temperature is in Kelvin and specific humidity in kg/kg
    temp_c = ds['temperature'] - 273.15
    specific_humidity = ds['specific_humidity']

    # Calculate relative humidity
    rh = calculate_relative_humidity(temp_c, specific_humidity)

    # Calculate Wet Bulb Temperature (WBT)
    wbt = xr.apply_ufunc(calculate_wbt, temp_c, rh,
                         input_core_dims=[[], []],
                         output_core_dims=[[]],
                         vectorize=True,
                         dask='parallelized',
                         output_dtypes=[float])

    # Add WBT to the dataset
    ds['wet_bulb_temperature'] = wbt

    # Classify precipitation type based on WBT
    precip_type = xr.where(ds['wet_bulb_temperature'] <= 0, 'snow', 'rain')

    # Add precipitation type to the dataset
    ds['precipitation_type'] = precip_type

    return ds
