In [1]:
import boto3
import s3fs
import xarray as xr
import fsspec
import numpy as np
import time

In [2]:
%%time
bucket_url = 's3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr'

# create an instace of the S3FileSystem class from s3fs and list files
s3 = boto3.client('s3')
s3_filesystem = s3fs.S3FileSystem(anon=True)
files = s3_filesystem.ls(f'{bucket_url}') 
files

CPU times: user 212 ms, sys: 195 ms, total: 407 ms
Wall time: 1.41 s


['noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr/',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr/.zattrs',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr/.zgroup',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr/.zmetadata',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr/RAINRATE',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr/crs',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr/time',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr/x',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr/y']

In [3]:
# Define the URL for the CONUS dataset
conus_bucket_url = 's3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/precip.zarr'


In [4]:
# Open the dataset using xarray and fsspec
precip_ds = xr.open_zarr(
        fsspec.get_mapper(
            conus_bucket_url,
            anon=True
        ),
        consolidated=True
)


In [5]:
# Print the dataset to inspect its contents
print(precip_ds)

<xarray.Dataset> Size: 27TB
Dimensions:   (time: 385704, y: 3840, x: 4608)
Coordinates:
  * time      (time) datetime64[ns] 3MB 1979-02-01 ... 2023-01-31T23:00:00
  * x         (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.303e+06 2.304e+06
  * y         (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.918e+06 1.919e+06
Data variables:
    RAINRATE  (time, y, x) float32 27TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    crs       |S1 1B ...
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing


In [6]:
%%time
bucket_url = 's3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr'

# create an instace of the S3FileSystem class from s3fs and list files
s3 = boto3.client('s3')
s3_filesystem = s3fs.S3FileSystem(anon=True)
files = s3_filesystem.ls(f'{bucket_url}') 
files

CPU times: user 15.2 ms, sys: 660 μs, total: 15.8 ms
Wall time: 57.1 ms


['noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr/',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr/.zattrs',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr/.zgroup',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr/.zmetadata',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr/T2D',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr/crs',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr/time',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr/x',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr/y']

In [7]:
%%time
conus_bucket_url = 's3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/t2d.zarr'

temp_ds = xr.open_zarr(
        fsspec.get_mapper(
            conus_bucket_url,
            anon=True
        ),
        consolidated=True
)

CPU times: user 1.55 s, sys: 66.8 ms, total: 1.62 s
Wall time: 5.03 s


In [8]:
print(temp_ds)

<xarray.Dataset> Size: 55TB
Dimensions:  (time: 385704, y: 3840, x: 4608)
Coordinates:
  * time     (time) datetime64[ns] 3MB 1979-02-01 ... 2023-01-31T23:00:00
  * x        (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.303e+06 2.304e+06
  * y        (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.918e+06 1.919e+06
Data variables:
    T2D      (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    crs      |S1 1B ...
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing


In [9]:
%%time
bucket_url = 's3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr'

# create an instace of the S3FileSystem class from s3fs and list files
s3 = boto3.client('s3')
s3_filesystem = s3fs.S3FileSystem(anon=True)
files = s3_filesystem.ls(f'{bucket_url}') 
files

CPU times: user 14.8 ms, sys: 993 μs, total: 15.8 ms
Wall time: 58.1 ms


['noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr/',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr/.zattrs',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr/.zgroup',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr/.zmetadata',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr/Q2D',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr/crs',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr/time',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr/x',
 'noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr/y']

In [10]:
%%time
conus_bucket_url = 's3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/forcing/q2d.zarr'

humid_ds = xr.open_zarr(
        fsspec.get_mapper(
            conus_bucket_url,
            anon=True
        ),
        consolidated=True
)

CPU times: user 1.63 s, sys: 47.6 ms, total: 1.68 s
Wall time: 5.15 s


In [11]:
humid_ds

<xarray.Dataset> Size: 55TB
Dimensions:  (time: 385704, y: 3840, x: 4608)
Coordinates:
  * time     (time) datetime64[ns] 3MB 1979-02-01 ... 2023-01-31T23:00:00
  * x        (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.303e+06 2.304e+06
  * y        (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.918e+06 1.919e+06
Data variables:
    Q2D      (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    crs      |S1 1B ...
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing

In [12]:
# Merge the datasets
combined_ds = xr.merge([temp_ds, precip_ds, humid_ds])

# Optionally, rename variables for clarity
combined_ds = combined_ds.rename({
    'T2D': 'temperature',
    'RAINRATE': 'total_precipitation',
    'Q2D': 'specific_humidity'
})

In [13]:
print(combined_ds)

<xarray.Dataset> Size: 136TB
Dimensions:              (time: 385704, y: 3840, x: 4608)
Coordinates:
  * time                 (time) datetime64[ns] 3MB 1979-02-01 ... 2023-01-31T...
  * x                    (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.304e+06
  * y                    (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.919e+06
Data variables:
    temperature          (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    crs                  |S1 1B b''
    total_precipitation  (time, y, x) float32 27TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    specific_humidity    (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing


In [14]:
import xarray as xr
import numpy as np
import dask.array as da

In [15]:
def calculate_wbt(temp_c, rh):
    # Empirical formula to approximate wet bulb temperature
    wbt = temp_c * np.arctan(0.151977 * np.sqrt(rh + 8.313659)) + \
          np.arctan(temp_c + rh) - np.arctan(rh - 1.676331) + \
          0.00391838 * (rh ** (3 / 2)) * np.arctan(0.023101 * rh) - 4.686035
    return wbt

In [16]:
# Ensure the dataset is loaded correctly
print("Combined Dataset Structure:")
print(combined_ds)

Combined Dataset Structure:
<xarray.Dataset> Size: 136TB
Dimensions:              (time: 385704, y: 3840, x: 4608)
Coordinates:
  * time                 (time) datetime64[ns] 3MB 1979-02-01 ... 2023-01-31T...
  * x                    (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.304e+06
  * y                    (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.919e+06
Data variables:
    temperature          (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    crs                  |S1 1B b''
    total_precipitation  (time, y, x) float32 27TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    specific_humidity    (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing


In [17]:
# Define the bounding box coordinates
min_x = -2303499.25
max_x = 2303500.75
min_y = -1919500.375
max_y = 1919499.625

In [18]:
# Subset the dataset to the bounding box and select data for January 2012
bbox_ds = combined_ds.sel(x=slice(min_x, max_x), y=slice(min_y, max_y), time=slice('2012-01-01', '2012-01-31'))
print("Bounding Box and January 2012 Subset Dataset Structure:")
print(bbox_ds)

Bounding Box and January 2012 Subset Dataset Structure:
<xarray.Dataset> Size: 263GB
Dimensions:              (time: 744, y: 3840, x: 4608)
Coordinates:
  * time                 (time) datetime64[ns] 6kB 2012-01-01 ... 2012-01-31T...
  * x                    (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.304e+06
  * y                    (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.919e+06
Data variables:
    temperature          (time, y, x) float64 105GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
    crs                  |S1 1B b''
    total_precipitation  (time, y, x) float32 53GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
    specific_humidity    (time, y, x) float64 105GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing


In [19]:
# Assuming temperature is in Kelvin and specific humidity in kg/kg
# Convert temperature to Celsius for the calculation
temp_c = bbox_ds['temperature'] - 273.15

In [20]:
# Calculate relative humidity directly from specific humidity without pressure
specific_humidity = bbox_ds['specific_humidity']
rh = specific_humidity / (1 + specific_humidity) * 100  # simplified calculation for relative humidity in %

In [21]:
# Calculate Wet Bulb Temperature (WBT) using Dask
wbt = xr.apply_ufunc(calculate_wbt, temp_c, rh,
                     input_core_dims=[[], []],
                     output_core_dims=[[]],
                     vectorize=True,
                     dask='parallelized',
                     output_dtypes=[float])

In [22]:
# Add WBT to the dataset
bbox_ds['wet_bulb_temperature'] = wbt

In [23]:
# Classify precipitation type based on WBT
precip_type = xr.where(wbt <= 0, 'snow', 'rain')

In [24]:
# Add precipitation type to the dataset
bbox_ds['precipitation_type'] = precip_type

In [25]:
# Print the structure of the updated dataset
print(bbox_ds)

<xarray.Dataset> Size: 579GB
Dimensions:               (time: 744, y: 3840, x: 4608)
Coordinates:
  * time                  (time) datetime64[ns] 6kB 2012-01-01 ... 2012-01-31...
  * x                     (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.304e+06
  * y                     (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.919e+06
Data variables:
    temperature           (time, y, x) float64 105GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
    crs                   |S1 1B b''
    total_precipitation   (time, y, x) float32 53GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
    specific_humidity     (time, y, x) float64 105GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
    wet_bulb_temperature  (time, y, x) float64 105GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
    precipitation_type    (time, y, x) <U4 211GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
  

In [26]:
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt

def calculate_wbt(temp_c, rh):
    # Empirical formula to approximate wet bulb temperature
    wbt = temp_c * np.arctan(0.151977 * np.sqrt(rh + 8.313659)) + \
          np.arctan(temp_c + rh) - np.arctan(rh - 1.676331) + \
          0.00391838 * (rh ** (3 / 2)) * np.arctan(0.023101 * rh) - 4.686035
    return wbt

# Define the original bounding box coordinates
min_x = -2303499.25
max_x = 2303500.75
min_y = -1919500.375
max_y = 1919499.625

# Subset the dataset to the bounding box and select data for January 2012
bbox_ds = combined_ds.sel(x=slice(min_x, max_x), y=slice(min_y, max_y), time=slice('2012-01-01', '2012-01-31'))
print("Bounding Box and January 2012 Subset Dataset Structure:")
print(bbox_ds)

# Assuming temperature is in Kelvin and specific humidity in kg/kg
# Convert temperature to Celsius for the calculation
temp_c = bbox_ds['temperature'] - 273.15

# Check sample dry bulb temperature values (in Celsius)
sample_temp_c = temp_c.isel(time=0, x=slice(0, 10), y=slice(0, 10)).values
print("Sample Dry Bulb Temperature Values (Celsius):")
print(sample_temp_c)

# Check sample specific humidity values
sample_humidity = bbox_ds['specific_humidity'].isel(time=0, x=slice(0, 10), y=slice(0, 10)).values
print("Sample Specific Humidity Values (kg/kg):")
print(sample_humidity)

# Calculate relative humidity more accurately
def calculate_relative_humidity(temp_c, specific_humidity):
    # Constants for water vapor pressure calculation
    A = 6.1121  # hPa
    B = 17.502
    C = 240.97  # degrees Celsius
    # Calculate saturation vapor pressure in hPa
    saturation_vapor_pressure = A * np.exp((B * temp_c) / (temp_c + C))
    # Calculate actual vapor pressure in hPa
    actual_vapor_pressure = specific_humidity * 1013.25 / (0.622 + 0.378 * specific_humidity)
    # Calculate relative humidity
    rh = (actual_vapor_pressure / saturation_vapor_pressure) * 100
    return rh

sample_rh_accurate = calculate_relative_humidity(sample_temp_c, sample_humidity)
print("Sample Relative Humidity Values (Accurate, %):")
print(sample_rh_accurate)

# Recalculate wet bulb temperature using the accurate relative humidity
sample_wbt_recalculated = calculate_wbt(sample_temp_c, sample_rh_accurate)
print("Recalculated Wet Bulb Temperature Values (Celsius):")
print(sample_wbt_recalculated)

# Calculate Wet Bulb Temperature (WBT) for the entire dataset
rh = calculate_relative_humidity(temp_c, bbox_ds['specific_humidity'])
wbt = xr.apply_ufunc(calculate_wbt, temp_c, rh,
                     input_core_dims=[[], []],
                     output_core_dims=[[]],
                     vectorize=True,
                     dask='parallelized',
                     output_dtypes=[float])

# Add WBT to the dataset
bbox_ds['wet_bulb_temperature'] = wbt

# Classify precipitation type based on WBT
precip_type = xr.where(wbt <= 0, 'snow', 'rain')

# Add precipitation type to the dataset
bbox_ds['precipitation_type'] = precip_type

# Print the structure of the updated dataset
print(bbox_ds)

Bounding Box and January 2012 Subset Dataset Structure:
<xarray.Dataset> Size: 263GB
Dimensions:              (time: 744, y: 3840, x: 4608)
Coordinates:
  * time                 (time) datetime64[ns] 6kB 2012-01-01 ... 2012-01-31T...
  * x                    (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.304e+06
  * y                    (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.919e+06
Data variables:
    temperature          (time, y, x) float64 105GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
    crs                  |S1 1B b''
    total_precipitation  (time, y, x) float32 53GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
    specific_humidity    (time, y, x) float64 105GB dask.array<chunksize=(432, 350, 350), meta=np.ndarray>
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing
Sample Dry Bulb Temperature Values (Celsius):
[[14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
 [14.85 14.85 14.85 14

In [27]:
import xarray as xr

# Load the combined dataset
combined_ds

# Check the structure of the dataset
print("Combined Dataset Structure:")
print(combined_ds)

# Print a sample of raw data values before any processing
raw_sample_temp = combined_ds['temperature'].isel(time=0, x=slice(0, 10), y=slice(0, 10)).values - 273.15
raw_sample_humidity = combined_ds['specific_humidity'].isel(time=0, x=slice(0, 10), y=slice(0, 10)).values

print("Sample Raw Temperature Values (Celsius):")
print(raw_sample_temp)

print("Sample Raw Specific Humidity Values (kg/kg):")
print(raw_sample_humidity)


Combined Dataset Structure:
<xarray.Dataset> Size: 136TB
Dimensions:              (time: 385704, y: 3840, x: 4608)
Coordinates:
  * time                 (time) datetime64[ns] 3MB 1979-02-01 ... 2023-01-31T...
  * x                    (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.304e+06
  * y                    (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.919e+06
Data variables:
    temperature          (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    crs                  |S1 1B b''
    total_precipitation  (time, y, x) float32 27TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    specific_humidity    (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing
Sample Raw Temperature Values (Celsius):
[[14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
 [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.8

In [28]:
import xarray as xr

# Load the combined dataset
combined_ds

# Check the structure of the dataset
print("Combined Dataset Structure:")
print(combined_ds)

# Check a small sample of raw data values directly from the source
raw_sample_temp = combined_ds['temperature'].isel(time=slice(0, 10), x=slice(0, 10), y=slice(0, 10)).values - 273.15
raw_sample_humidity = combined_ds['specific_humidity'].isel(time=slice(0, 10), x=slice(0, 10), y=slice(0, 10)).values

print("Sample Raw Temperature Values (Celsius):")
print(raw_sample_temp)

print("Sample Raw Specific Humidity Values (kg/kg):")
print(raw_sample_humidity)


Combined Dataset Structure:
<xarray.Dataset> Size: 136TB
Dimensions:              (time: 385704, y: 3840, x: 4608)
Coordinates:
  * time                 (time) datetime64[ns] 3MB 1979-02-01 ... 2023-01-31T...
  * x                    (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.304e+06
  * y                    (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.919e+06
Data variables:
    temperature          (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    crs                  |S1 1B b''
    total_precipitation  (time, y, x) float32 27TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    specific_humidity    (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing
Sample Raw Temperature Values (Celsius):
[[[14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85]
  [14.85 14.85 14.85 14.85 14.85 14.85 14.85 14.85 14

In [29]:
import xarray as xr

# Load the combined dataset
combined_ds

# Verify the dimensions and coordinates
print("Dimensions:", combined_ds.dims)
print("Coordinates:", combined_ds.coords)

# Access a specific variable and print a sample
temp_sample = combined_ds['temperature'].isel(time=0).values
humidity_sample = combined_ds['specific_humidity'].isel(time=0).values

print("Temperature Sample:", temp_sample)
print("Specific Humidity Sample:", humidity_sample)


Dimensions: FrozenMappingWarningOnValuesAccess({'time': 385704, 'y': 3840, 'x': 4608})
Coordinates: Coordinates:
  * time     (time) datetime64[ns] 3MB 1979-02-01 ... 2023-01-31T23:00:00
  * x        (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.303e+06 2.304e+06
  * y        (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.918e+06 1.919e+06
Temperature Sample: [[288. 288. 288. ... 288. 288. 288.]
 [288. 288. 288. ... 288. 288. 288.]
 [288. 288. 288. ... 288. 288. 288.]
 ...
 [288. 288. 288. ... 288. 288. 288.]
 [288. 288. 288. ... 288. 288. 288.]
 [288. 288. 288. ... 288. 288. 288.]]
Specific Humidity Sample: [[0.005 0.005 0.005 ... 0.005 0.005 0.005]
 [0.005 0.005 0.005 ... 0.005 0.005 0.005]
 [0.005 0.005 0.005 ... 0.005 0.005 0.005]
 ...
 [0.005 0.005 0.005 ... 0.005 0.005 0.005]
 [0.005 0.005 0.005 ... 0.005 0.005 0.005]
 [0.005 0.005 0.005 ... 0.005 0.005 0.005]]


In [30]:
import xarray as xr

# Load the combined dataset
combined_ds

# Print the structure of the dataset
print("Combined Dataset Structure:")
print(combined_ds)

# Check other variables to see if they have uniform values
precip_sample = combined_ds['total_precipitation'].isel(time=0).values

print("Sample Raw Precipitation Values (mm):")
print(precip_sample)


Combined Dataset Structure:
<xarray.Dataset> Size: 136TB
Dimensions:              (time: 385704, y: 3840, x: 4608)
Coordinates:
  * time                 (time) datetime64[ns] 3MB 1979-02-01 ... 2023-01-31T...
  * x                    (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.304e+06
  * y                    (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.919e+06
Data variables:
    temperature          (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    crs                  |S1 1B b''
    total_precipitation  (time, y, x) float32 27TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    specific_humidity    (time, y, x) float64 55TB dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing
Sample Raw Precipitation Values (mm):
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 